version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: gestionventas
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my_network

  app:
    build: .
    image: cristianorizano10/backend-gestionventas:latest
    restart: always
    ports:
      - "8091:8091"
    environment:
      DB_URL: jdbc:mysql://db:3306/gestionventas?serverTimezone=America/Lima
      DB_USER_NAME: root
      DB_PASSWORD: mysql
    depends_on:
      - db
    networks:
      - my_network

volumes:
  mysql_data:
    driver: local

networks:
  my_network:
    driver: bridge